[pytest]
pythonpath = .

markers =
    slow: marque un test comme lent

filterwarnings =
    # Ignore les DeprecationWarnings qui viennent de docling
    ignore::DeprecationWarning:docling.*:
    ignore::DeprecationWarning:rapidocr_onnxruntime.*:
    # Ignore le warning du CPU pour Whisper
    ignore::UserWarning:whisper.*: